on: push
name: Release Build
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BT_DIR: ${{ github.workspace }}/BATTLETECH
      MANAGED_DIR: ${{ github.workspace }}/BATTLETECH/BattleTech_Data/Managed
    steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '6.0.x'
    - name: Download Dependencies
      env:
        MANAGED_ARCHIVE_PW: ${{ secrets.MANAGED_ARCHIVE_PW }}
        MANAGED_ARCHIVE_URL: ${{ secrets.MANAGED_ARCHIVE_URL }}
      run: |
        curl -L -o Managed.7z "$MANAGED_ARCHIVE_URL"
        mkdir -p "$MANAGED_DIR/"
        7z e -p"$MANAGED_ARCHIVE_PW" -o"$MANAGED_DIR/" Managed.7z
    - name: Checkout
      uses: actions/checkout@master
      with:
        path: ModTek/
    - name: Fetch Branches and Tags
      run: cd ModTek/ && git fetch --prune --unshallow
    - name: Build
      run: |
        cd ModTek/
        dotnet build --verbosity normal --configuration Release -p:BattleTechGameDir="$BT_DIR/"
        rm -fr "$BT_DIR/BattleTech_Data/"
        cd "$BT_DIR/"
        find . -type f -printf "%m:%p\n"
        # set permissions and also check if files exist
        chmod 755 run.sh
        chmod 644 winhttp.dll
        chmod 644 Mods/ModTek/ModTekPreloader.dll
        chmod 644 Mods/ModTek/ModTek.dll
        chmod 644 Mods/ModTek/Injectors/ModTekInjector.dll
        7z a -tzip -mx9 ../ModTek.zip -ir!.
    - name: Upload Artifact
      uses: actions/upload-artifact@main
      with:
        name: ModTek
        path: |
          BATTLETECH
          BATTLETECH/BattleTech_Data/Managed
    - name: Release Latest
      uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/master'
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        title: "Latest (unstable)"
        prerelease: true
        files: ModTek.zip
    - name: Release Tag
      uses: softprops/action-gh-release@master
      if: startsWith(github.ref, 'refs/tags')
      with:
        draft: false
        prerelease: false
        body: |
          ### Important
          **ModTekInjector.exe was replaced by UnityDoorstop**, [UnityDoorstop](https://github.com/NeighTools/UnityDoorstop) works by just copying files to the games directory. Running any injectors exes is not necessary or allowed anymore.
          
          ModTek.zip contains the ModTek tools, please unzip them as directly into your game's location.
          see [Changes](https://github.com/BattletechModders/ModTek/blob/master/CHANGES.md)
        files: ModTek.zip
