on: push
name: Release Build
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BT_DIR: ${{ github.workspace }}/BATTLETECH
      MANAGED_DIR: ${{ github.workspace }}/BATTLETECH/BattleTech_Data/Managed
    steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '6.0.x'
    - name: Download Dependencies
      env:
        MANAGED_ARCHIVE_PW: ${{ secrets.MANAGED_ARCHIVE_PW }}
        MANAGED_ARCHIVE_URL: ${{ secrets.MANAGED_ARCHIVE_URL }}
      run: |
        curl -L -o Managed.7z "$MANAGED_ARCHIVE_URL"
        mkdir -p "$MANAGED_DIR/"
        7z e -p"$MANAGED_ARCHIVE_PW" -o"$MANAGED_DIR/" Managed.7z
    - name: Checkout
      uses: actions/checkout@master
      with:
        path: ModTek/
    - name: Fetch Branches and Tags
      run: cd ModTek/ && git fetch --prune --unshallow
    - name: Build
      run: |
        cd ModTek/
        dotnet build -c Release -p:BattleTechGameDir="$BT_DIR/" -p:OutputPath="$BT_DIR/Mods/ModTek"
        rm -fr "$BT_DIR/BattleTech_Data/"
        cd "$BT_DIR/"
        chmod 755 run.sh
        find . -type f -printf "%m:%p\n"
        7z a -tzip -mx9 ../ModTek.zip -ir!.
    - name: Upload Artifact
      uses: actions/upload-artifact@main
      with:
        name: ModTek
        path: |
          BATTLETECH
          BATTLETECH/BattleTech_Data/Managed
    - name: Release Latest
      uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/master'
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        title: "Latest (unstable)"
        prerelease: true
        files: ModTek.zip
    - name: Release Tag
      uses: softprops/action-gh-release@master
      if: startsWith(github.ref, 'refs/tags')
      with:
        draft: false
        prerelease: false
        body: |
          ModTek.zip contains the ModTek tools, please unzip them as directly into your games location.
          see [Changes](https://github.com/BattletechModders/ModTek/blob/master/CHANGES.md)
        files: ModTek.zip
