name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/mod-builder.yml
    with:
      checkout-directory: 'ModTek'
      modtek-download-url: '' # don't download ModTek when ModTek is being built!
      build-script: |
        build_modtek() {
          btdir="$1"
          zipname="$2"
          dotnet build --verbosity normal --configuration Release -p:BattleTechGameDir="$btdir"
          cd "$btdir"
          rm -fr "BattleTech_Data/"
          find . -type f -printf "%m:%p\n"
          # set permissions and also check if files exist (chmod 644)
          chmod 755 run.sh
          chmod 644 winhttp.dll
          chmod 644 Mods/ModTek/lib/*.dll
          7z a -tzip -mx9 "$DIST_DIR/$zipname" -ir!.
          cd -
          dotnet clean --verbosity normal --configuration Release -p:BattleTechGameDir="$btdir"
        }
        
        BATTLETECH_DIR_OLD_HARMONY="${BATTLETECH_DIR}oldharmony"
        cp -a "$BATTLETECH_DIR" "$BATTLETECH_DIR_OLD_HARMONY"
        build_modtek "$BATTLETECH_DIR" "ModTek.zip"
        
        OLD_HARMONYX_VERSION="2.10.2"
        sed -i -r -e 's/Include="HarmonyX" Version="[^"]+?"/Include="HarmonyX" Version="'$OLD_HARMONYX_VERSION'"/g' Directory.Packages.props
        build_modtek "$BATTLETECH_DIR_OLD_HARMONY" "ModTek-old-HarmonyX-${OLD_HARMONYX_VERSION}.zip"
      release-notes: |
        > **Note**
        > **ModTekInjector.exe was replaced by [UnityDoorstop](https://github.com/NeighTools/UnityDoorstop)**.
        > Injectors must not be run manually, that is now done by the `ModTekPreloader` automatically during the games startup.
        
        ModTek.zip contains the ModTek tools. Unzip the contents into your game's location, so that `winhttp.dll` appears in the same folder as `BattleTech.exe`.
        See [Changes](https://github.com/BattletechModders/ModTek/blob/master/CHANGES.md) and [Readme](https://github.com/BattletechModders/ModTek/blob/master/README.md).
    secrets: inherit
